dataset_config:
  synsin_habitat:
    data_dir: ${env.data_dir}/datasets
    # dummy options to turn off the default image and feature loader in MMF
    fast_read: false
    use_images: false
    use_features: false

    multiview_data_dir: /checkpoint/ronghanghu/neural_rendering_datasets/synsin_mp3d
    multiview_image_dir: /checkpoint/ronghanghu/neural_rendering_datasets/synsin_mp3d
    num_view_per_sample: 2
    annotations:
        train:
        - synsin_habitat/defaults/annotations/imdb_mp3d_train.npy
        val:
        - synsin_habitat/defaults/annotations/imdb_mp3d_mini_train.npy
        test:
        - synsin_habitat/defaults/annotations/imdb_mp3d_val.npy
    processors:
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
            # ToTensor is not needed has we have already handled uint8 to float and HWC to CHW in the dataset
            - type: Normalize
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
