includes:
- ./realestate10k_defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.005
      image_l1_1_inpaint: 800
      vgg19_perceptual_1_inpaint: 200
    mesh_laplacian_use_l2_loss: false
    use_inpainting: true
    inpainting:
      net_G:
        use_alpha_input: true
        norm: batch

distributed:
  convert_bn_to_sync_bn: true

dataset_config:
  synsin_realestate10k:
    train_video_list: /checkpoint/ronghanghu/neural_rendering_datasets/realestate10K/RealEstate10K/frames/train/video_loc_short.txt