includes:
- ./realestate10k_defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.005
      image_l1_1_inpaint: 20
      vgg19_perceptual_1_inpaint: 200
      gan: 20  # should be the same as "gan_feat" to follow pix2pixHD
      gan_feat: 20  # note that there's also a lambda_feat: 10.0 applied on this loss within gan_loss
    z_pred_scaling: 2.0
    z_pred_offset: 0.0
    mesh_laplacian_use_l2_loss: false
    use_inpainting: true
    inpainting:
      net_G:
        use_alpha_input: true
        norm: batch
        optimizer:
          lr: 1e-4
      use_discriminator: true
      net_D:
        norm: batch
        optimizer:
          lr: 1e-2
        gan_mode: hinge

distributed:
  convert_bn_to_sync_bn: true

training:
  clip_gradients: false

checkpoint:
  reset:
    all: true  # only keep the model parameters, reset iteration number and optimizer, etc
  resume_file: ./save/synsin_realestate10k/realestate10k_nodepth_perceptual_l1laplacian_inpaintGonly_scale2/best.ckpt
