includes:
- ./mp3d_defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.01
      image_l1_1_inpaint: 800
      vgg19_perceptual_1_inpaint: 200
    mesh_laplacian_use_l2_loss: false
    grid_stride: 4
    use_inpainting: true
    inpainting:
      net_G:
        use_alpha_input: true
        norm: batch

distributed:
  convert_bn_to_sync_bn: true

checkpoint:
  reset:
    all: true  # only keep the model parameters, reset iteration number and optimizer, etc
  resume_file: ./save/synsin_habitat/mp3d_nodepth_stride4ft_perceptual_l1laplacian/init.ckpt
