includes:
- ./mp3d_defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 0.
      mesh_laplacian: 0.01
    mesh_laplacian_use_l2_loss: false
