model_config:
  mesh_renderer:
    z_min: 0.2
    z_max: 100.
    z_pred_scaling: 10.0
    rendering:
      hfov: 45
      z_background: 15.79283931454195  # Diode mean depth
      background_color: [0.41809689, 0.3559381, 0.29154181]  # Diode mean RGB
    loss_weights:
      z_grid_l1_0: 20  # 1/z_pred_scaling of Replica to have the same loss scale
      depth_l1_0: 20  # 1/z_pred_scaling of Replica to have the same loss scale
      depth_l1_1: 20  # 1/z_pred_scaling of Replica to have the same loss scale
      image_l1_1: 0.
      grid_offset: 5
      mesh_laplacian: 0.0025
    mesh_laplacian_use_l2_loss: false
    grid_stride: 4

optimizer:
  type: adam_w  # HuggingFace transformer's AdamW
  params:
    lr: 1e-4
    eps: 1e-8
    weight_decay: 1e-5

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 25000
    - 28000
    lr_ratio: 0.2
    warmup_iterations: 500
    warmup_factor: 0.25

training:
  num_workers: 2
  clip_norm_mode: all
  clip_gradients: true
  max_grad_l2_norm: 5
  lr_scheduler: true
  max_updates: 30000
  checkpoint_interval: 5000
  evaluation_interval: 5000
  log_interval: 20
  batch_size: 64
  early_stop:
    enabled: false
    criteria: total_loss
    minimize: true
  stdout_capture: false
  find_unused_parameters: true
  log_format: json
  tensorboard: false
