includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.01
      image_l1_1_inpaint: 800
      vgg19_perceptual_1_inpaint: 200
    mesh_laplacian_use_l2_loss: false
    use_inpainting: true
    sanity_check_inpaint_with_gt: true
    inpainting:
      net_G:
        generate_img_residual: false

training:
  max_updates: 10000  # 10000 iters should be sufficient for sanity check