# require an issue template to be chosen
blank_issues_enabled: false

contact_links:
  - name: Worldsheet Documentation
    url: https://github.com/facebookresearch/worldsheet
    about: Check if your issue/documentation is already answered in the Readme
