includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 200
      depth_l1_0: 200
      depth_l1_1: 200
      image_l1_1: 400
      grid_offset: 5
      mesh_laplacian: 0.0025
    mesh_laplacian_use_l2_loss: false
    grid_stride: 4
    rendering:
      blur_radius: 1e-8