includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.01
      image_l1_1_inpaint: 40
      vgg19_perceptual_1_inpaint: 200
      gan: 40  # should be the same as "gan_feat" to follow pix2pixHD
      gan_feat: 40  # note that there's also a lambda_feat: 10.0 applied on this loss within gan_loss
    mesh_laplacian_use_l2_loss: false
    use_inpainting: true
    inpainting:
      net_G:
        use_alpha_input: true
        norm: batch
      use_discriminator: true
      net_D:
        use_alpha_input: true
        norm: batch

scheduler:
  type: pix2pixHD
  params:
    constant_lr_iterations: 27500
    total_iterations: ${training.max_updates}

distributed:
  convert_bn_to_sync_bn: true