includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.01
      image_l1_1_inpaint: 800
      vgg19_perceptual_1_inpaint: 200
      gan: 20  # should be the same as "gan_feat" to follow pix2pixHD
      gan_feat: 20  # note that there's also a lambda_feat: 10.0 applied on this loss within gan_loss, so it's actual weight is 200
    mesh_laplacian_use_l2_loss: false
    use_inpainting: true
    inpainting:
      net_G:
        use_alpha_input: true
        generate_img_residual: true
      use_discriminator: true