includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.01
      image_l1_1_inpaint: 0.
      vgg19_perceptual_1_inpaint: 0.
      gan: 40  # should be the same as "gan_feat" to follow pix2pixHD
      gan_feat: 0.
    mesh_laplacian_use_l2_loss: false
    use_inpainting: true
    inpainting:
      net_G:
        use_alpha_input: true
        norm: batch
      use_discriminator: true
      net_D:
        norm: batch