includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      grid_offset: 5
      mesh_laplacian: 0.0025
    grid_stride: 4
    rendering:
      blur_radius: 1e-8
