includes:
- ./defaults.yaml

model_config:
  mesh_renderer:
    loss_weights:
      z_grid_l1_0: 0.
      depth_l1_0: 0.
      depth_l1_1: 0.
      image_l1_1: 800
      vgg19_perceptual_1: 200
      grid_offset: 20
      mesh_laplacian: 0.01
    mesh_laplacian_use_l2_loss: false

dataset_config:
  replica:
    annotations:
      train:
      - replica/defaults/annotations/imdb_train.npy
      - replica/defaults/annotations/imdb_large_baseline_train.npy

checkpoint:
  reset:
    all: true  # only keep the model parameters, reset iteration number and optimizer, etc
  resume_file: ./save/replica/only_image_l1_loss_perceptual_l1laplacian/current.ckpt
